version: "3.3"

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: prueba
      MYSQL_USER: SergioE
      MYSQL_PASSWORD: contrapass
      MYSQL_ROOT_PASSWORD: contrapass1

    ports:
      - "3307:3306"
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: sergio123
    ports:
      - "8080:80"

  mytest_django:
    image: python:3.9.5
    container_name: test_django
    restart: always
    volumes:
      - type: bind
        source: .
        target: /opt/back_end

    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
